# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pipelines',
                'doc_host': 'https://oguiza.github.io',
                'git_url': 'https://github.com/oguiza/pipelines',
                'lib_path': 'pipelines'},
  'syms': {'pipelines.core': {'pipelines.core.foo': ('core.html#foo', 'pipelines/core.py')}}}
